[package]
name = "hyperx-monitor"
version = "1.0.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"
eframe = { version = "0.35.0", features = ["wgpu"] }
hidapi = "2.6.4"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"]}
clap = { version = "4.6.5", features = ["derive"] }
